### ISSUE TITLE
not support node v6+

### ISSUE THREAD

**Issue by sabakugaara** [ex-machine/express-ko#1]
```
TypeError: Iterator result undefined is not an object
   at /Users/hubiao/project/ng-admin/node_modules/express-ko/lib/index.js:91:18
   at next (native)
   at onFulfilled (/Users/hubiao/project/ng-admin/node_modules/co/index.js:65:19)
   at /Users/hubiao/project/ng-admin/node_modules/co/index.js:54:5
   at co (/Users/hubiao/project/ng-admin/node_modules/co/index.js:50:10)
   at Function.koifyHandler [as ifyHandler] (/Users/hubiao/project/ng-admin/node_modules/express-ko/lib/index.js:89:14)
   at Layer.handle [as handle_request] (/Users/hubiao/project/ng-admin/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/hubiao/project/ng-admin/node_modules/express/lib/router/index.js:312:13)
   at /Users/hubiao/project/ng-admin/node_modules/express/lib/router/index.js:280:7
   at next (/Users/hubiao/project/ng-admin/node_modules/express/lib/router/index.js:271:10)
   at /Users/hubiao/project/ng-admin/node_modules/express-session/index.js:473:7
   at /Users/hubiao/project/ng-admin/node_modules/connect-redis/lib/connect-redis.js:160:14
   at tryCatcher (/Users/hubiao/project/ng-admin/node_modules/bluebird/js/release/util.js:16:23)
   at Promise.successAdapter [as _fulfillmentHandler0] (/Users/hubiao/project/ng-admin/node_modules/bluebird/js/release/nodeify.js:23:30)
   at Promise._settlePromise (/Users/hubiao/project/ng-admin/node_modules/bluebird/js/release/promise.js:564:21)
   at Promise._settlePromise0 (/Users/hubiao/project/ng-admin/node_modules/bluebird/js/release/promise.js:612:10)
```

**Comment by bisubus** [comment]
Thanks for reporting. I'm not sure if the issue can be linked to Node version. Can you set up a simple repo to reproduce the problem?

**Comment by sabakugaara** [comment]
How can I run the test case?  `gulp test` execute failed

**Comment by bisubus** [comment]
I've updated the package, there was an outdated dev dependency (nodegit) that prevented tests from running on Node 6.

**Comment by bisubus** [comment]
I will close it for now. Please, reopen if the issue persists and can be replicated.
